### ISSUE TITLE
Possible to build and link against ZeroMQ on macOS?

### ISSUE THREAD

**Issue by nlyan** [steve-o/openpgm#45]
Is it possible to build and link current versions against ZeroMQ 4.2? I've been trying for over 2 hours and can't seem to get ZeroMQ to link with the static library Scons generates.

I'm attempting this because the last release seems to be completely broken on macOS (see: https://github.com/zeromq/libzmq/issues/2205 ).

Any guidance would be appreciated.

**Comment by steve-o** [comment]
The HEAD of master branch should build correctly on OSX, the branch mainly contains bug fixes for building on newer platforms and configurations.  ZeroMQ bundles a tarball but can also use an external path when running `configure`.

**Comment by sigiesec** [comment]
I needed to apply some fixes to build under MacOS X: https://github.com/sigiesec/openpgm/commit/e5b1d977d3d3ae5950e94eb5e4779c3d40ec1f01

What confuses me a bit here that version_generator.py definitely contains a syntax error.

**Comment by rgundo** [comment]
This line in version_generator.py  is missing a paren at the end:
timestamp = time.gmtime(int(os.environ.get('SOURCE_DATE_EPOCH',
time.time()))     )<===

That fixed it for me

**Comment by sigiesec** [comment]
@rgundo I needed to change that but also two C files.

_Sent from my Honor FRD-L09 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by steve-o** [comment]
Any chance of a pull request so I can cleanup head?  Thanks.

**Comment by sigiesec** [comment]
I created #50, but please check this thoroughly.
